### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAIntTensor instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by S200331082** [aioz-ai/MICCAI19-MedVQA#10]
has anyone encountered this problem?
Any comment (even though it’s short!) or just listing keywords to look at will be highly appreciated!
![image](https://user-images.githubusercontent.com/74856789/123909863-37e09700-d9ac-11eb-9886-81b739557bd4.png)

**Comment by S200331082** [comment]
add```.long()```in the wrong part

**Comment by hamzakhalil798** [comment]
@S200331082 Did you find the solution? Im running into same error
