### ISSUE TITLE
How to get pretrained MAML weights

### ISSUE THREAD

**Issue by famishedfish** [aioz-ai/MICCAI19-MedVQA#11]
Hello,
Thank you for your kind sharing. I'm trying to reproduce this paper but having some troubles.
In base_model.py line 164, the code `maml_v_emb.load_state_dict(torch.load(weight_path))` loads pretrained weights for MAML, but I can't find the corresponding .pth file.
I tried to load `pretrained_maml.weights`, but the weights from this file are inconsistent with the structure of MAML model.
Here are my questions:
* How can I obtain the .pth file to initialize MAML correctly, or am I expected to train it from scratch?
* Since `pretrained_maml.weights` doesn't seem to be used to initialize MAML, what's the use of it?

Thanks a lot.

**Comment by xuanbinh-nguyen96** [comment]
Hello,
Thank you for your interest in our work.

We provided the "pretrained_maml.weights" (not .pth) file in data_RAD ([link](https://vision.aioz.io/f/777a3737ee904924bf0d/?dl=1)) (Preprocessing step in README).
We also re-run the source code. There are not any problems. Please follow the instructions step by step (REAME).

Sincerely,

**Comment by famishedfish** [comment]
I thought this was because I am running your 21-year work at the same time, so I confuse the data of them😂
I re-clone the repository and run successfully this time.
And thank you for your reply.
