### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data_RAD/imgid2idx.json'  

### ISSUE THREAD

**Issue by Yead** [aioz-ai/MICCAI19-MedVQA#2]
I downloaded the dataset from the [link](https://osf.io/89kps/), then split the json file into trainset.json and test.json, but still can not find imgid2idx.json. When I run 
`python3 main.py --model SAN --use_RAD --RAD_dir data_RAD --maml --autoencoder --output saved_models/SAN_MEVF            
`
FileNotFoundError: [Errno 2] No such file or directory: 'data_RAD/imgid2idx.json'  

Could you please show where I can get imgid2idx.json?

**Comment by binhnd-aioz** [comment]
Hi Yead,
You should download the preprocessed data via this link [https://vision.aioz.io/f/777a3737ee904924bf0d/?dl=1](link).
