### ISSUE TITLE
Didn't find the train_cdae.py in your codes.

### ISSUE THREAD

**Issue by Amling2017** [aioz-ai/MICCAI19-MedVQA#7]
hi, I didn't find the train_cdae.py.  May I get it? Thank you!

**Comment by hannajiang** [comment]
hello, I can't open the link of dataset. Can you tell me where to get unlabelled data for pretraining? thank you

**Comment by xuanbinh-nguyen96** [comment]
Due to some restrictions in our company policy, the data used for auto encoder and its following source codes used in this paper to learn auto encoder model can not be shared yet. I will inform you later whenever I can share them to you. So sorry for this problem!

**Comment by Amling2017** [comment]
ok! Thanks for your reply!
